services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MONGO_PASSWORD: coffeeShop5
      NODE_ENV: development
    ports:
      - "7000:7000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_PORT: 5173
