version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "7000:7000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/yourdb

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
